# Use the official Node.js image as the base image for backend
FROM node:20.0.0-alpine AS backend

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

RUN mkdir -p /data/db

# EXPOSE 27017

COPY quirknotes/backend ./data/db

FROM mongo:latest

RUN mongod --dbpath=./data/db

# run server
RUN npm run dev

